version: '3.8'
services:
  dev-db:
    image: postgres:13
    container_name: desafio-backend
    ports:
      - 5432:5432
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defafio
    networks:
      - backendjr
  
networks:
  backendjr:
